# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newDialog(object):
    def setupUi(self, newDialog):
        newDialog.setObjectName("newDialog")
        newDialog.resize(454, 222)
        self.Title = QtWidgets.QLineEdit(newDialog)
        self.Title.setGeometry(QtCore.QRect(130, 70, 241, 31))
        self.Title.setObjectName("Title")
        self.Text = QtWidgets.QLineEdit(newDialog)
        self.Text.setGeometry(QtCore.QRect(130, 120, 241, 31))
        self.Text.setObjectName("Text")
        self.Label2 = QtWidgets.QLabel(newDialog)
        self.Label2.setGeometry(QtCore.QRect(70, 80, 55, 16))
        self.Label2.setObjectName("Label2")
        self.Lable3 = QtWidgets.QLabel(newDialog)
        self.Lable3.setGeometry(QtCore.QRect(70, 130, 55, 16))
        self.Lable3.setObjectName("Lable3")
        self.Date = QtWidgets.QDateTimeEdit(newDialog)
        self.Date.setGeometry(QtCore.QRect(130, 20, 241, 31))
        self.Date.setObjectName("Date")
        self.Label1 = QtWidgets.QLabel(newDialog)
        self.Label1.setGeometry(QtCore.QRect(70, 30, 55, 16))
        self.Label1.setObjectName("Label1")
        self.Save = QtWidgets.QPushButton(newDialog)
        self.Save.setEnabled(True)
        self.Save.setGeometry(QtCore.QRect(170, 170, 121, 41))
        self.Save.setAutoDefault(False)
        self.Save.setObjectName("Save")

        self.retranslateUi(newDialog)
        QtCore.QMetaObject.connectSlotsByName(newDialog)

    def retranslateUi(self, newDialog):
        _translate = QtCore.QCoreApplication.translate
        newDialog.setWindowTitle(_translate("newDialog", "New remind"))
        self.Label2.setText(_translate("newDialog", "Title"))
        self.Lable3.setText(_translate("newDialog", "Text"))
        self.Label1.setText(_translate("newDialog", "Date"))
        self.Save.setText(_translate("newDialog", "Save"))